### ISSUE TITLE
Add temporary security credentials without IAM policy

### ISSUE THREAD

**Issue by shawnhankim** [nginxinc/nginx-s3-gateway#100]
**Is your feature request related to a problem? Please describe.**
As a Software Engineer,
- Currently, I can run `nginx-s3-gateway` using AWS Access key id and secret access key without an IAM Policy.
- In addition to that I want to run and test it either in a container or on a laptop using temporary security credentials which include a session token.

**Describe the solution you'd like**
- Read a session token from the environment variable of `S3_SESSION_TOKEN` if the variable exists and is not empty.
- Otherwise, set to `null` to return credentials which only contain AWS access key ID and secret key.

**Describe alternatives you've considered**
- In case the `S3_SESSION_TOKEN` isn't specified in your AWS profile, the `nginx-s3-gateway` can be accessed using access key id and secret access key as is.

**Additional context**
- This PR is used when a session token is required to access your service without an IAM Policy as the following picture.

<img width="791" alt="credentials-example" src="https://user-images.githubusercontent.com/39923730/222021471-62ba8919-b0b7-41ea-a500-ccc75ec51c3a.png">

**Comment by dekobon** [comment]
Fixed in #101
