### ISSUE TITLE
Invalid path while cloning repo

### ISSUE THREAD

**Issue by zc-devs** [nginxinc/nginx-s3-gateway#128]
**Describe the bug**
Cannot clone repository on Windows. There is an `error: invalid path 'test/data/bucket-1/a/%@!*()=$#^&|.txt'`. Repository is empty and all files are deleted.

**To Reproduce**
1. Have a Windows and installed Git SCM.
2. Try to clone repo
```
$ git clone https://github.com/nginxinc/nginx-s3-gateway.git
Cloning into 'nginx-s3-gateway'...
remote: Enumerating objects: 1388, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1388 (delta 28), reused 53 (delta 22), pack-reused 1318
Receiving objects: 100% (1388/1388), 1.01 MiB | 309.00 KiB/s, done.
Resolving deltas: 100% (599/599), done.
```
3. See error
```
error: invalid path 'test/data/bucket-1/a/%@!*()=$#^&|.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
4. Inspect the repo

Empty directory:
```
$ cd nginx-s3-gateway/ && ls -lah
total 4.0K
drwxr-xr-x 1 user 104 0 May 13 18:40 ./
drwxr-xr-x 1 user 104 0 May 13 18:40 ../
drwxr-xr-x 1 user 104 0 May 13 18:40 .git/
```

Deleted files:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    .github/ISSUE_TEMPLATE/bug_report.md
        deleted:    .github/ISSUE_TEMPLATE/feature_request.md
        deleted:    .github/workflows/main.yml
        deleted:    .gitignore
        deleted:    CODE_OF_CONDUCT.md
        deleted:    CONTRIBUTING.md
        deleted:    Dockerfile.buildkit.plus
...
```

**Expected behavior**
Repository is cloned without errors, branch is checked out without errors, files exist in the repo.

**Your environment**
* Version of the OS - Windows 10, 22H2, x64
* Version of the git - Git SCM, 2.40.0.windows.1
* Version of the repo - master branch (2fd4fa4d0b5962c10d615d3dc7c43733ca3eb3b8)

**Comment by dekobon** [comment]
Thank you for submitting this. What a fascinating error! That file exists in order to test problematic file paths. Apparently, it is too problematic for Windows file systems. Do you have a workaround in place? In order to fix this, we will probably have to generate problematic filenames and conditionally not generate some of them when running on Windows.

**Comment by zc-devs** [comment]
> Do you have a workaround?

Yes, there is:
```
$ git restore --staged .
error: invalid path 'test/data/bucket-1/a/%@!*()=$#^&|.txt'

$ git restore --source=HEAD :/
error: invalid path 'test/data/bucket-1/a/%@!*()=$#^&|.txt'

$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    test/data/bucket-1/a/%@!*()=$#^&|.txt

$ git commit -m "Deleted file with wrong name on Windows"
[master 70d2d3f] Deleted file with wrong name on Windows
```

> We will probably have to generate problematic filenames and conditionally not generate some of them when running on Windows.

It would be great.

I'll exchange PR with cache configuration from Environment for this fix ;)

**Comment by dekobon** [comment]
Did you find any other "offending" files?

**Comment by zc-devs** [comment]
No, only this one. But I didn't run tests.
