### ISSUE TITLE
Support for Ceph Object Storage Gateway

### ISSUE THREAD

**Issue by axoxymous-coder** [nginxinc/nginx-s3-gateway#130]
Hi,

Is nginx-s3-gateway supported with Ceph Object Storage Gateway? I tried using it with Ceph, but it always errors out with AWS EC2 credentials not found. My Ceph cluster is created using Rook in local K8s cluster. 

Here are the settings I am using for Ceph:

```
S3_BUCKET_NAME=mybucket
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXX
AWS_SECRET_KEY=YYYYYYYYYYYYYYYYYYYYYYYYYYYYY
S3_SERVER=172.17.0.1
S3_SERVER_PORT=31185
S3_SERVER_PROTO=http
S3_REGION=us-east-1
AWS_SIGS_VERSION=4
ALLOW_DIRECTORY_LIST=true
S3_STYLE=virtual
DEBUG=true
PROVIDE_INDEX_PAGE=false
APPEND_SLASH_FOR_POSSIBLE_DIRECTORY=true
PROXY_CACHE_VALID_OK=1h
PROXY_CACHE_VALID_NOTFOUND=1m
PROXY_CACHE_VALID_FORBIDDEN=30s
```

Does nginx-s3-gateway only works in AWS environment for S3? In the document however its mentioned that it works for all S3 compatible object storage systems.

Any help will be highly appreciated.

**Comment by dekobon** [comment]
Can you check that you are running the latest version of the gateway? Preferably you are running from the images from github (not dockerhub). This error looks a lot like an error that was fixed recently.

**Comment by dekobon** [comment]
Did this solve your problem?

**Comment by mxm-tr** [comment]
In case you are stil having issues: lI think that `S3_STYLE` has to be configured with "path" for it to work with Ceph RADOS Gateway.

**Comment by dekobon** [comment]
I'm going to make this as closed. If you are still having problems, please comment or reopen the issue.
