### ISSUE TITLE
Unable to run docker image

### ISSUE THREAD

**Issue by artem-v-shamsutdinov** [nginxinc/nginx-s3-gateway#14]
I'm unable to run the docker image (I'm new to both Docker and nginx).  Here is what I did:

1.  Clone the repository
2.  Create a "settings" file with:

S3_BUCKET_NAME=my-bucket-name
S3_ACCESS_KEY_ID=my-access-key-id
S3_SECRET_KEY=my-secret-key
S3_SERVER=s3.amazonaws.com
S3_SERVER_PORT=443
S3_SERVER_PROTO=https
S3_REGION=us-west-1
S3_STYLE=virtual
S3_DEBUG=false
AWS_SIGS_VERSION=4
ALLOW_DIRECTORY_LIST=false

3.  Built:
docker build -f Dockerfile.oss -t nginx-oss-s3-gateway .

4.  Attempted to run with specified command:

docker run --env-file ./settings -p8080:80 --name nginx-oss-s3-gateway nginx-s3-gateway 
Unable to find image 'nginx-s3-gateway:latest' locally
docker: Error response from daemon: pull access denied for nginx-s3-gateway, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

5.  Attempted to modify the run command:
docker run -p8080:80 --env-file ./settings nginx-oss-s3-gateway 
standard_init_linux.go:228: exec user process caused: no such file or directory

I'm using Docker Destop 3.5.2 on Windows 10.  A basic docker file with nginx:latest (and just a copy of index.html file into the image) works.

Not sure what I'm doing wrong, please help. :)

**Comment by artem-v-shamsutdinov** [comment]
Never mind, built on Ubuntu subsystem and it worked, must be a Windows only issue.

**Comment by qq524967747** [comment]
vim docker-entrypoint.sh and 00-check-for-required-env.sh, input :set ff=unix,  rebuild dockerfile
