### ISSUE TITLE
standalone_ubuntu_oss_install fail on listing.xsl.template download

### ISSUE THREAD

**Issue by orensharoni** [nginxinc/nginx-s3-gateway#148]
**Describe the bug**
standalone_ubuntu_oss_install.sh script fails in line 378 
in the download directive for common/etc/nginx/include/listing.xsl.template 
getting a 404 and stopping the install script

**To Reproduce**
1. clone the master branch of the repo
2. run ./standalone_ubuntu_oss_install.sh
3. See error - script stops at  Creating NGINX configuration for S3 Gateway

**Expected behavior**
finish the install process or echo the error to the screen 

installing on wsl2 ubuntu 22.04
using master

**Comment by orensharoni** [comment]
my workaround was this change 
download "common/etc/nginx/include/listing.xsl" "/etc/nginx/include/listing.xsl.template"

**Comment by zc-devs** [comment]
Thanks for attention. It's regression from  #135. Fix is absolutely correct.
