### ISSUE TITLE
With Directory listing turned on query parameters cause 500 errors

### ISSUE THREAD

**Issue by coreyfellows** [nginxinc/nginx-s3-gateway#164]
**Describe the bug**
With Directory listing turned on query parameters cause 500 errors

**To Reproduce**
1. Start container with APPEND_SLASH_FOR_POSSIBLE_DIRECTORY=true and ALLOW_DIRECTORY_LIST=true with an S3 bucket with an empty index.html at `/test/index.html`
2. Run the container and navigate to /test/?asdf=asdf
3. 500 error at s3PreListing

**Expected behavior**
Should show the content of index.html

**Your environment**
Container is the latest release
Deployed on AWS EC2 with EKS with AWS S3 as the backend

**Comment by dekobon** [comment]
I've verified this issue as reproducible. I hope to be able to do a root cause analysis soon. If anyone has insights into the cause of the issue, posting them in the comments would be quite welcome.

**Comment by coreyfellows** [comment]
I suspect the issue is using `request_uri` here. I believe it includes the query parameters and that wrecks it when appending the index.html.

https://github.com/nginxinc/nginx-s3-gateway/blob/7e35275d04e6da0198958b2344da75e41c6940ed/common/etc/nginx/include/s3gateway.js#L363C66-L363C66

**Comment by dekobon** [comment]
@coreyfellows Can you verify if the PR #167 fixes the issue for you in your environment?

**Comment by 4141done** [comment]
@coreyfellows Quick question for you. Given your expectation described in the bug report, do you also have `PROVIDE_INDEX_PAGE` enabled?  I've written up my understanding of your expectations in this draft PR I made while reviewing https://github.com/nginxinc/nginx-s3-gateway/pull/167.

My understanding is that without `PROVIDE_INDEX_PAGE` we'd expect to see a directory list with `index.html` as an item in this case.

You can see it here: https://github.com/nginxinc/nginx-s3-gateway/pull/169

**Comment by 4141done** [comment]
@coreyfellows A fix for this bug report has been merged.  If the problem persists in the new version please reopen this issue.  Thank you for your contribution to the project.
