### ISSUE TITLE
nginx: [emerg] invalid IPv6 address in resolver "[NOTE:]" in /etc/nginx/conf.d/upstreams.conf:2

### ISSUE THREAD

**Issue by jdoig** [nginxinc/nginx-s3-gateway#171]
**Describe the bug**
Poorly constrained `grep` in the bash scripts seems to pick up a comment from the `/etc/resolv.conf` file.

**To Reproduce**
1. Start container ```docker run --env-file ./settings --publish 8011:80 --name nginx-s3-gateway nginx-s3-gateway:oss```
2. View logs
3. See error:
```
2023/09/13 11:50:22 [emerg] 1#1: invalid IPv6 address in resolver "[NOTE:]" in /etc/nginx/conf.d/upstreams.conf:2
nginx: [emerg] invalid IPv6 address in resolver "[NOTE:]" in /etc/nginx/conf.d/upstreams.conf:2
```

**Expected behavior**
The server starts as expected.

**Your environment**
* Local clone of the master branch at time of writing.

**Additional context**
See this line beginning with `# NOTE` and ending in `nameservers`...
```
nameserver 8.8.4.4
nameserver 94.198.184.14
nameserver 94.198.184.34
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 8.8.8.8
```
 ... it qualifies for the `grep` commands found here: https://github.com/search?q=repo%3Anginxinc%2Fnginx-s3-gateway%20%22grep%20nameserver%22&type=code
**Sensitive Information**

**Comment by dekobon** [comment]
Thank you for reporting this!

**Comment by thresheek** [comment]
We probably should be using https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/15-local-resolvers.envsh instead
