### ISSUE TITLE
Arm64 build

### ISSUE THREAD

**Issue by maxemann96** [nginxinc/nginx-s3-gateway#196]
**Is your feature request related to a problem? Please describe.**
I want to run a kubernetes cluster with only arm64 nodes, as a result I need an arm64 build for every software I use.

**Describe the solution you'd like**
Also building a docker image for arm64

**Describe alternatives you've considered**
No alternatives

**Additional context**
The nginx base image is already available as arm64

Thanks in advance for creating and maintaining this image. Very useful for my use case.

**Comment by 4141done** [comment]
Hello!

Thank you for bringing this up! It is on my list of things to do but having someone complain certainly helps with prioritization.  You should see this change coming in fairly soon.  See my reply to [this issue](https://github.com/nginxinc/nginx-s3-gateway/issues/195#issuecomment-1879106854) regarding a refactor I'm doing at the moment to decouple the integration tests from the build process and move the integration test suite into Javascript.  I'm tracking that work here: https://github.com/nginxinc/nginx-s3-gateway/issues/191

**Comment by hmehta** [comment]
Hi!

This would be so wonderful! We are moving from AMD64->ARM64 and this is one of the few things we are using that not yet supports ARM64. So a big upvote from here for bumping this up a notch on the todo list :)

**Comment by ehginanjar** [comment]
Hi @maxemann96 

I've had similar case, building the image so I can test it on my M1 Pro. In this case I used docker, so I tried to build the image by using this command `docker buildx build --platform linux/arm64`. So maybe this solution can be tested on your side as well. Cheers!

**Comment by 4141done** [comment]
@maxemann96 and @hmehta :  I have a provisional PR for an overhaul of the build and test pipeline in case you have comments here: https://github.com/nginxinc/nginx-s3-gateway/pull/197
You don't necessarily have to review it but any comments are welcome.

More importantly, it produced a test image that you can see here: https://github.com/nginxinc/nginx-s3-gateway/pkgs/container/nginx-s3-gateway%2Fnginx-oss-s3-gateway/166168166?tag=latest-new-build-test

Would you mind testing to see if this works for you?

**Comment by maxemann96** [comment]
@4141done the test image is running properly, thanks :)

**Comment by hmehta** [comment]
@4141done I confirm that the image works for us too. Thanks a lot!

**Comment by 4141done** [comment]
Thank you both for confirming.  Arm64 images will start being built after that PR is merged.  I'm just waiting on code review from my co-maintainers.
