### ISSUE TITLE
Removes the path in the URL

### ISSUE THREAD

**Issue by krishk8s** [nginxinc/nginx-s3-gateway#219]
**Describe the bug**
I am trying to access s3 bucket objects (not a website) hosted on S3 bucket.
Using EKS to access the files via nginx-ingress controller
I can access the files and folders, but when i click on subfolder it's removing the path.. here is an example:

so https://hostme.com/something works and i can see folder1 and folder2 in there, but when i click on folder1 it removed the "something" in the url and obviously the path is not right and i get error

Ingress will be /something is pointing to the nginx-s3-gateway service on kubernetes

**Expected behavior**
To keep the path consistently for all sub-folder and files

i did tried adding STRIP_LEADING_DIRECTORY_PATH to "/something"... but it's not working as expected
also tried DIRECTORY_LISTING_PATH_PREFIX='main/' still the same..

When i port-forward, it's behaving as expected, it's via nginx-ingress is the issue here, obviously it's behind  NLB

**Your environment**

* S3 backend implementation you are using - AWS S3 bucket
* How you are deploying : EKS
* NGINX type (OSS)
* Authentication method (IRSA - IAM Role with ServiceAccount and working as expected)
* nginx-ingress-Controller - trying to access the files via ingress on kubernetes

Thanks
Krish

**Comment by jlevablue** [comment]
@krishk8s did you ever find a fix or work around for this? I am having a similar issue
