### ISSUE TITLE
`nginx: [emerg] open() "/etc/nginx/conf.d/gateway/s3_location_common.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:1`

### ISSUE THREAD

**Issue by akashgreninja** [nginxinc/nginx-s3-gateway#222]
**Describe the bug**
On running the standalone_ubuntu_oss_install.sh script i get the below error 
`nginx: [emerg] open() "/etc/nginx/conf.d/gateway/s3_location_common.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:1`
.

**To Reproduce**
1. i copied the  standalone_ubuntu_oss_install.sh script on my x86_64 x86_64 x86_64 GNU/Linux vm
2. ran the `sudo env $(cat settings.env) sh s3-gateway.sh`  command 
3. Saw the above error 

**Expected behavior**
It was supposed to start the nginx server with all configured s3 gateway 

**Your environment**
* x86_64 x86_64 x86_64 GNU/Linux 

**Additional context**
i did fix it by adding the missing file ie 
`touch  /etc/nginx/conf.d/gateway/s3_location_common.conf`
and it started working as expected

**Comment by 4141done** [comment]
Hi @akashgreninja , thank you for reporting this bug.  I have pushed a fix for the bug here https://github.com/nginxinc/nginx-s3-gateway/pull/226

Apologies for any confusion this may have caused.
