### ISSUE TITLE
Support AWS S3 Express One Zone

### ISSUE THREAD

**Issue by 4141done** [nginxinc/nginx-s3-gateway#225]
**Is your feature request related to a problem? Please describe.**
The S3 Gateway should provide support for  AWS S3 Express One Zone

**Describe the solution you'd like**
Users should be able to attach the gateway to  AWS S3 Express One Zone or normal s3-compatible object stores with roughly the same configuration if possible

**Additional context**
Relevant discussion: https://github.com/nginxinc/nginx-s3-gateway/discussions/220

**Comment by hveiga** [comment]
Hi @4141done I opened https://github.com/nginxinc/nginx-s3-gateway/pull/228 to add support for S3 Express. After some research I found out the missing pieces and how to make them work. Looking for feedback on the approach, as I believe it can be improved. Thanks.

**Comment by 4141done** [comment]
Thanks to @hveiga 's contribution we were able to implement compatibility https://github.com/nginxinc/nginx-s3-gateway/pull/229

For usage instructions see this section of the readme: https://github.com/nginxinc/nginx-s3-gateway/blob/master/docs/getting_started.md#user-content-choosing-a-s3_style-setting

The session-based auth is not implemented.  I've added an issue for it here https://github.com/nginxinc/nginx-s3-gateway/issues/233
