### ISSUE TITLE
Filenames with brackets () return 404 errors

### ISSUE THREAD

**Issue by sixem** [nginxinc/nginx-s3-gateway#53]
Hi,

I'm running the the stand-alone container on one of my servers. Problem is, whenever one of the files stored in the S3 container contains brackets, the gateway will return a 404 error.

An example:

Both `image.jpg` and `image(1).jpg` exists in the same bucket in the same folder.

This:
```bash
curl -I "http://127.0.0.1:8011/image.jpg"
```
Returns:
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 31 Aug 2022 17:45:21 GMT
Content-Type: image/jpeg
Content-Length: 466483
Connection: keep-alive
Last-Modified: Wed, 31 Aug 2022 17:44:50 GMT
ETag: "b34cf0ebd821a9f892b361e6812571eb"
Accept-Ranges: bytes
```
While this:
```bash
curl -I "http://127.0.0.1:8011/image(1).jpg"
```
Returns:
```
HTTP/1.1 404 Not Found
Server: nginx
Date: Wed, 31 Aug 2022 17:45:27 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive
```

The gateway log shows this:
```
127.0.0.1 - - [31/Aug/2022:17:45:21 +0000] "HEAD /image.jpg HTTP/1.1" 200 0 "-" "curl/7.64.0" "-"
2022/08/31 17:45:21 [info] 61#61: *159 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [31/Aug/2022:17:45:27 +0000] "HEAD /image(1).jpg HTTP/1.1" 404 0 "-" "curl/7.64.0" "-"
2022/08/31 17:45:27 [info] 61#61: *161 client 127.0.0.1 closed keepalive connection
```

Server details:
```
Debian 8.3.0-6 GNU/Linux 10 (buster)
Linux version 4.19.0-14-cloud-amd64
```

**Comment by dekobon** [comment]
Hi @sixem ,

What S3 service are you using on the backend? Is it AWS S3 or something else?

**Comment by sixem** [comment]
> Hi @sixem ,
> 
> What S3 service are you using on the backend? Is it AWS S3 or something else?

I'm using AWS S3.

**Comment by cpeled** [comment]
Hi,
it seems that the same happens for every escaped uri path.
the s3 url is generated correctly (i compared it with aws s3 object url) but probably something is wrong with the canonical v4 request.
if i comment out the redirection of all errors to 404, i see aws s3 returns "403 FORBIDDEN".

thanks.

**Comment by dekobon** [comment]
Hi @cpeled , can you please provide some examples that fail?

**Comment by cpeled** [comment]
Hi @dekobon
I have a file name with Hebrew letters - חן The gw encodes it correctly and generates the Uri as expected, I compared it with the aws s3 url of the object. 
But the v4 signed request ends with 403 from the S3 endpoint url.

**Comment by cpeled** [comment]
> Hi @cpeled , can you please provide some examples that fail?

Hi @dekobon , any update regarding this issue?

best,
Chen

**Comment by dekobon** [comment]
Hi @cpeled , I've been off on PTO and now I'm back at the keyboard. This will take some work to set up the tests to show failure and then debug. If anyone in the community wants to take it on, it may get resolved quicker than relying on me to resolve it.

This is the rough order of work that I would imagine needs to be done:
 1. Add integration tests illustrating the failure with Minio.
 2. Add unit tests illustrating the failure with pure njs style Javascript.
 3. Debug and attempt to fix without breaking other encoding cases.
 4. Reproduce error on AWS and perhaps another object store like Wasabi or Backblaze.

**Comment by dekobon** [comment]
Closing this PR in favor of this PR: https://github.com/nginxinc/nginx-s3-gateway/pull/58

**Comment by dekobon** [comment]
Oops! I meant to close the PR not the issue. Reopening.

**Comment by dekobon** [comment]
Closing this PR in favor of this PR: https://github.com/nginxinc/nginx-s3-gateway/pull/58

**Comment by dekobon** [comment]
Oops! I meant to close the PR not the issue. Reopening.
