### ISSUE TITLE
Cloudflare R2 error

### ISSUE THREAD

**Issue by endnch** [nginxinc/nginx-s3-gateway#78]
**Describe the bug**
I'm getting the following errors when using Cloudflare R2;
`2022/12/11 16:15:46 [error] 64#64: *1 SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream`
`2022/12/11 16:15:46 [warn] 64#64: *1 upstream server temporarily disabled while SSL handshaking to upstream`

I can fix the errors and it works fine if I add the following line to `default.conf` (inside `location @s3`):
`proxy_ssl_server_name on;`
and "hardcoding" my R2 domain in proxy pass:
`proxy_pass https://abcdefghijklmnopqrstuvwxz1234567.r2.cloudflarestorage.com$s3uri;`
but having to do that everytime I restart the container is a PITA.

Posting this issue so maybe a kind sould can fix it or post a better solution.

**Your environment**
* Version of the repo - a specific commit or tag
latest-20221104

* Version of the container used (if downloaded from Docker Hub or Github)
ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:latest

* S3 backend implementation you are using (AWS, Ceph, NetApp StorageGrid, etc)
Cloudflare R2

* How you are deploying Docker/Stand-alone, etc
Docker

* NGINX type (OSS/Plus)
OSS

* Authentication method (IAM, IAM with Fargate, IAM with K8S, AWS Credentials, etc)
Secret and access keys

**Comment by dekobon** [comment]
Thank you for reporting this issue. First, I think there is a way for you to get the container to use the configuration you mentioned above without having to rewrite it every time it starts. I would extend the s3 gateway docker image and then in your own Dockerfile overwrite the [stub files](https://github.com/nginxinc/nginx-s3-gateway/blob/master/docs/development.md#stub-files) for the [/etc/nginx/conf.d/s3_location.conf stub file](https://github.com/nginxinc/nginx-s3-gateway/blob/master/common/etc/nginx/templates/gateway/s3_server.conf.template).

Secondly, I want to try to enable `proxy_ssl_server_name` by default, but before that, I'm trying to figure out why you must hardcode the server name. Can you share with me the non-sensitive environment variables you used when starting the gateway container image?

**Comment by endnch** [comment]
Here's my .env:

```
S3_BUCKET_NAME=my-bucket
S3_ACCESS_KEY_ID=*redacted*
S3_SECRET_KEY=*redacted*
S3_SERVER=*redacted*.r2.cloudflarestorage.com
S3_SERVER_PORT=443
S3_SERVER_PROTO=https
S3_REGION=us-east-1
AWS_SIGS_VERSION=4
S3_STYLE=path
ALLOW_DIRECTORY_LIST=false
S3_DEBUG=true
DNS_RESOLVERS=8.8.8.8
```

**Comment by dekobon** [comment]
Looking at your settings above, I suspect that you should change:
```
S3_SERVER=*redacted*.r2.cloudflarestorage.com
```
to:
```
S3_SERVER=.r2.cloudflarestorage.com
```

If `*redacted*` is the name of your bucket. Also, does the `virtual` `S3_STYLE` not work on R2?

Please try to make that change and then let me know if you no longer need to modify the `proxy_pass` directive arguments.

**Comment by endnch** [comment]
Actually, *redacted* is my R2 Account ID not the name of my bucket.

**Comment by dekobon** [comment]
Please try this. Revert the `proxy_pass` line to the original value, leave ` proxy_ssl_server_name on;` setting in place and change the environment variable so that it is`S3_STYLE=virtual`.

**Comment by dekobon** [comment]
I've enabled SNI via the `proxy_ssl_server_name on;` directive by default now. This was done in commit 8366ab87ff92ca3aa013b018f3445294e2e30a53.

**Comment by endnch** [comment]
> Please try this. Revert the `proxy_pass` line to the original value, leave ` proxy_ssl_server_name on;` setting in place and change the environment variable so that it is`S3_STYLE=virtual`.

I tried and I get the same SSL error.

**Comment by dekobon** [comment]
I got an account on backblaze and debugged the issue. It appears that we need to set `proxy_ssl_name` in addition to `proxy_ssl_server_name`. Please try the latest image without any modifications.

**Comment by endnch** [comment]
I'm getting the following error now:

```
s3-gateway  | 2022/12/15 03:50:29 [notice] 70#70: http file cache: /var/cache/nginx/s3_proxy 0.000M, bsize: 4096
s3-gateway  | 2022/12/15 03:50:29 [notice] 1#1: signal 17 (SIGCHLD) received from 70
s3-gateway  | 2022/12/15 03:50:29 [notice] 1#1: cache loader process 70 exited with code 0
s3-gateway  | 2022/12/15 03:50:29 [notice] 1#1: signal 29 (SIGIO) received
```

My .env:
```
S3_BUCKET_NAME=*redacted*
S3_ACCESS_KEY_ID=*redacted*
S3_SECRET_KEY=*redacted*
S3_SERVER=*redacted*.r2.cloudflarestorage.com
S3_SERVER_PORT=443
S3_SERVER_PROTO=https
S3_REGION=us-east-1
AWS_SIGS_VERSION=4
S3_STYLE=path
ALLOW_DIRECTORY_LIST=false
S3_DEBUG=true
DNS_RESOLVERS=8.8.8.8
```

Same if I change `S3_STYLE` to `virtual`.

**Comment by dekobon** [comment]
Please pull the latest image and set `S3_REGION=auto` and try again. My apologies for the back and forth on this issue. I hope this solves it for you.

**Comment by endnch** [comment]
It works now if I set `S3_STYLE=path`. Thank you so much for taking the time to solve my issue 😃

**Comment by dekobon** [comment]
Fixed by:
8366ab87ff92ca3aa013b018f3445294e2e30a53
c4212dfe772f3bab5e9677d48c30e7efcdad9b0a
