### ISSUE TITLE
updated metadata headers are not served until a restart

### ISSUE THREAD

**Issue by mvanholsteijn** [nginxinc/nginx-s3-gateway#87]
**Describe the bug**
When you change the metadata information on an object (eg Cache-Control), the headers are not served until a restart of container image.

**To Reproduce**
1. start nginx
2. curl to an object on the bucket, check Cache-Control header is missing
```
curl -D - -o /dev/null http://nginx-s3-gateway/image.jpg
```
3. update all objects
```
aws s3  cp s3://bucket  s3://bucket \
   --recursive \
   --metadata-directive REPLACE \
   --exclude "*" \
   --include "*.jpg" \
   --cache-control public,max-age=1209600 \
   --content-type image/jpeg
```

4. All .jpg objects now metadata headers
5. curl to after the 5min cache time. Still no cache header.
```
curl -D - -o /dev/null http://nginx-s3-gateway/image.jpg
```
6. restart the nginx container
7. Presto! Cache-Control header of the object appears
```
curl -D - -o /dev/null http://nginx-s3-gateway/image.jpg
```

**Expected behavior**
we expect the cache-control header to appear

**Your environment**
* Version of the repo - a specific commit or tag
ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:latest-njs-oss-20220815
* Version of the container used (if downloaded from Docker Hub or Github)
ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:latest-njs-oss-20220815
* S3 backend implementation you are using (AWS, Ceph, NetApp StorageGrid, etc)
AWS
* How you are deploying Docker/Stand-alone, etc
k8s
* NGINX type (OSS/Plus)
no
* Authentication method (IAM, IAM with Fargate, IAM with K8S, AWS Credentials, etc)
AWS Credentials

**Comment by dekobon** [comment]
Hi @mvanholsteijn, I did a test, and it turns out that S3 does not change the `ETag` header when you update object metadata as you have done above, so from an HTTP cache contract point of view, the object hasn't changed, and does not need to be purged from the cache.

I know that is a poor answer, and it doesn't solve your problem, yet I'm not sure I have a solution other than periodic cache purges.

**Comment by jeffdyke** [comment]
To test this sort of thing there is nothing wrong with an `s3 mv .... .... --flags-go-here`.  I'm not saying libraries can't solve this, but i've found it easier to solve on my own.

**Comment by dekobon** [comment]
Closing because I am not sure that the S3 Gateway can do anything to change the behavior.
