### ISSUE TITLE
Is it possible get list of files in the path

### ISSUE THREAD

**Issue by artful88533** [nginxinc/nginx-s3-gateway#9]
Hi!
Thanks for a great app!

Private HTML file opens nice:
http://127.0.0.1/2021/test.html
![image](https://user-images.githubusercontent.com/19188399/117940544-d5efa380-b311-11eb-8e6e-388b6b67f223.png)

But when I open http://127.0.0.1/2021/ - it responses 404
![image](https://user-images.githubusercontent.com/19188399/117940781-1818e500-b312-11eb-9ae2-c9a70d7354b7.png)

Is it possible to get a list of files?

Thank you!

**Comment by artful88533** [comment]
How can I see, it isn't possible

```
    # Do not proxy requests for directories because we are not providing
    # directory listings nor do we want to reveal the application/x-directory
    # content type which will leak to the requester that we are proxying S3.
```

**Comment by dekobon** [comment]
The configuration as it is right now doesn't support file listing. However, if is probably possible to implement using [njs](https://nginx.org/en/docs/njs/). This would be a good pull request.

**Comment by artful88533** [comment]
it works!
Thanks a lot!
